### ISSUE TITLE
Streaming Directory Archives

### ISSUE THREAD

**Issue by Lazarus404** [dgvncsz0f/zipflow#2]
Hi,

Firstly, this project is perfect for my needs, provided it does what I want ;-)  I need to be able to zip a directory and stream that to the user (in Phoenix).  I've seen the example using File.open, but do you know if it's possible to pass a directory to archive?

Thanks,
Lee

**Comment by dgvncsz0f** [comment]
Hi Lazarus404,

this is a nice ideia. I'll add a directory_entry on the project so you can use it directly. I guess I could have it ready by tomorrow. The idea I'm thinking is to scan the directory [probably recursively] and on each file emit a file_entry. I'll let you know!

Thanks,
~dsouza

**Comment by Lazarus404** [comment]
Excellent.  I think that would be a very valuable addition

**Comment by Lazarus404** [comment]
Has there been any luck on this front?  :-)

**Comment by dgvncsz0f** [comment]
Hi Lazarus404,

sorry taking this long to get back to you. I was traveling and with no access to my computer that is why.

I should be able to fix this tonight. I'll let you now!

Best!
~dsouza

**Comment by Lazarus404** [comment]
Awesome.  I'll gladly test this for you.  I want to include it in a Phoenix application and have it stream a zip file based on passed folder path.

Thanks,
Lee

**Comment by dgvncsz0f** [comment]
Hi Lazarus404,

I've created https://github.com/dgvncsz0f/zipflow/pull/3 to track this. I have a working code already but it is missing tests and documentation. I'm guessing it takes one more day of work to make a release. I'll let you now.

~dsouza

**Comment by Lazarus404** [comment]
This is great, thanks 👍   This should make a difference.

Regards,
Lee

**Comment by dgvncsz0f** [comment]
Hi Lazarus404,

the new code is on master. 
https://github.com/dgvncsz0f/zipflow/blob/master/lib/zipflow/os.ex

Let me know if that works for you. If everything works fine I'll bump the version and make a release on hex.

Thanks!
~dsouza

**Comment by Lazarus404** [comment]
Awesome.  I'll be implementing it at the beginning of the week.

Thanks,
Lee

**Comment by Lazarus404** [comment]
Hi dsouza,

So, I'm using this with Plug in Phoenix, but I'm missing something because it won't end the stream.  The code I'm using to test is:

```
  def file_zip(conn, %{"dir" => dir}, _current_user, _claims) do
    conn = conn
    |> put_resp_content_type("application/octet-stream")
    |> send_chunked(200)

    read_file = fn d ->
      {:ok, conn} = Plug.Conn.chunk(conn, d)
      receive do
        {:update, data} ->
          Plug.Conn.chunk(conn, data)
        _ ->
      end
    end
    Zipflow.Stream.init
    |> Zipflow.OS.dir_entry(read_file, dir, [])
    |> Zipflow.Stream.flush(read_file)
  end
```

Do you see anything obvious?

Many thanks,
Lee

**Comment by Lazarus404** [comment]
It's always the simple things that throw you.  I wasn't returning "conn".  Okay, so the result that works, for anyone else wanting to do this, is:

```
def file_zip(conn, %{"dir" => dir}, _current_user, _claims) do
    conn = conn
    |> put_resp_content_type("application/octet-stream")
    |> send_chunked(200)

    chunk_file = fn d ->
     {:ok, conn} = chunk(conn, d)
    end
    Zipflow.Stream.init
    |> Zipflow.OS.dir_entry(chunk_file, dir, [])
    |> Zipflow.Stream.flush(chunk_file)

    conn
  end
```

Lee

**Comment by Lazarus404** [comment]
So, this works great, with one slight bug :-)  When specifying a directory to zip - for instance "./priv/static/site-files/pdfs", the zip will create folders for all the directories leading up to that, so it ends up containing "/Users/lee/Documents/zipflow-test/priv/static/site-files/pdfs/..."

What would be better is if the zip is named after the directory being zipped (pdfs) and contains just that directory and everything in it.

Otherwise, it's fantastic.  Thank you very much 👍

**Comment by dgvncsz0f** [comment]
Hi! I've added an option to control that:

https://github.com/dgvncsz0f/zipflow/blob/master/lib/zipflow/os.ex#L54
https://github.com/dgvncsz0f/zipflow/blob/master/test/zipflow/os/os_test.exs#L27

You can provide a function under the key `rename` which takes the original path name. the result is what gets added to the zip. The default is the identity function.

You can also filter which files to include using the `accept` function. The default is to accept all files.

Let me know if that helps!

~dsouza

**Comment by Lazarus404** [comment]
Sorry, I'm not sure I explained the problem properly.  The name of the zip is fine; it's the content that's a little wrong.  The zip doesn't just contain the directory tree from the point of the path supplied.  It also contains the parent directories up to the root of the server.  So, rather than just:

```
my_download/files/...
```

I get:

```
/root/website/downloadable/my_download/files/...
```

when supplied with the path `./downloadable/my_download`

Thanks,
Lee

**Comment by dgvncsz0f** [comment]
Oh I see. You can achieve that using the function I mention but I realize that is not very intuitive. I will make a patch today change the behavior to the way you expect.

Thanks!
~dsouza

**Comment by Lazarus404** [comment]
Awesome :-)  Thanks!

**Comment by dgvncsz0f** [comment]
Lazarur404,

I've pushed a patch on master. Relative paths should work as you expect. Give it a try and let me know.

Thx!
~dsouza

**Comment by Lazarus404** [comment]
Thanks dsouza,

I've incorporated it.  I'm currently rebuilding my file management microservice, so I'll let you know once the tests are refactored.

Thanks,
Lee

**Comment by Lazarus404** [comment]
Hi dsouza,

So, this is better, but still not quite right.  So, at the moment, I have a file at:

```
/Users/lee/Documents/project/files/images/example.png
```

I pass the path of:

```
./files/images
```

This should ideally zip `images` so the zip contains:

```
images -> example.png
```

However, instead, it contains:

```
files -> images -> example.png
```

Thanks,
Lee

**Comment by dgvncsz0f** [comment]
I based the implementation on how `zip/tar` commands work. when you pass relative path like that you get the same relative path as prefix. So I followed that same ideia.

That said, you can still achieve that using the rename function:

```
root = Path.expand("files")
...
|> Zipflow.OS.dir_entry(..., "./files/image", [rename: & Path.relative_to(&1, root)])
```

Sounds reasonable?

~dsouza

**Comment by Lazarus404** [comment]
Hi dsouza,

If I do that, it actually goes back to storing the full path `/Users/lee/...`, rather than just the immediate directory.

Thanks,
Lee

**Comment by dgvncsz0f** [comment]
It should work. That is how I've implemented the relative paths in the last commit.

Probably the `root` is not a proper parent of the files in that `rename` function I supose. Can you share that part of the code? I can help you debugging it. Also, if you don't mind, would you `IO.inspect` both `&1` and `root` variables?

Thanks,
~dsouza

**Comment by dgvncsz0f** [comment]
Hi Lazarus404,

do you need any more help or code change on this? Can we close it?

Thanks,
~dsouza

**Comment by Lazarus404** [comment]
Hi,

Please keep it open for now.  I've been rushed off my feet and haven't had
time to debug it.  I'll try to get to it today and will update you.

Regards,
Lee

**Comment by dgvncsz0f** [comment]
Sure, take your time. Just let me know if you need any more help!

~dsouza

**Comment by Lazarus404** [comment]
Hey dsouza,

This can be closed. It's all good. I think it might be worth adding this to the Readme for working with Phoenix file downloads.

### Download directory
```
  def download_path(conn, path) do
    conn = conn
      |> put_resp_content_type(Plug.MIME.type("zip"))
      |> send_chunked(200)
    chunk_file = fn d ->
      {:ok, conn} = chunk(conn, d)
    end
    basepath = Path.absname(path)
    rename = &Path.relative_to(&1, basepath)
    Zipflow.Stream.init
      |> Zipflow.OS.dir_entry(chunk_file, path, [rename: rename])
      |> Zipflow.Stream.flush(chunk_file)
    conn
  end
```

### Download list of paths
```
  def download_path_list(conn, paths) do
    basepath = paths |> List.first() |> Path.dirname() |> Path.absname()
    conn = conn
      |> put_resp_content_type(Plug.MIME.type("zip"))
      |> put_resp_header("content-disposition", "attachment; filename=#{Path.basename(basepath)}.zip")
      |> send_chunked(200)
    chunk_file = fn d ->
      {:ok, conn} = chunk(conn, d)
    end
    rename = &Path.relative_to(&1, basepath)
    context = Zipflow.Stream.init
    Enum.reduce(paths, context, fn(path, ctx) ->
      path = Path.absname(path)
      if File.dir?(path),
        do: Zipflow.OS.dir_entry(ctx, chunk_file, path, [rename: rename]),
      else: Zipflow.OS.file_entry(ctx, chunk_file, rename.(path), path)
    end)
      |> Zipflow.Stream.flush(chunk_file)
    conn
  end
```

Thanks for the great library!

Lee

**Comment by dgvncsz0f** [comment]
nice! thanks!
